### ISSUE TITLE
Add `WeedFSImageField`

### ISSUE THREAD

**Issue by khorolets** [ProstoKSI/django-weed#3]
Hi!

What do you think about introducing `WeedFSImageField`?

I'm using [`django-imagekit`](https://github.com/matthewwithanm/django-imagekit).

Here is the example.

```python
class User(AbstractBaseUser, PermissionsMixin):
    avatar = WeedFSFileField(_('Avatar'))
    avatar_big = ImageSpecField(
        source='avatar',
        processors=[ResizeToFit(275, 275)],
        format='JPEG',
        options={'quality': 100}
    )
```

This works with `ImageField` like a charm. When I try to use `WeedFSFileField` it fails because `ImageSpecField` seems to be relying on some `ImageField` specific methods.

For my purposes, I'm going to add `WeedFSImageField` with necessary methods for `django-imagekit` to work properly. 

What do you think about it? Would you be interested in PR with such field?

Thanks!

**Comment by frol** [comment]
I would avoid extra dependencies to only support a pretty specific use-case. However, if it only takes to extend a few interfaces to mimic the `ImageField`, let's give it a try.

P.S. If those resized images are not frequently accessed, I would consider using Nginx to resize and cache those images on the fly: https://stumbles.id.au/nginx-dynamic-image-resizing-with-caching.html.

**Comment by khorolets** [comment]
It's not so simple and this method doesn't work. Sorry for bothering and thanks for pointing to nginx.
